# 放可变的配置 比如阈值 路径 列名 特征开关等
# config/config.yaml
paths:
  raw: data/raw
  interim: data/interim
  processed: data/processed
  reports: reports
  neo4j_import: neo4j/import

ids:
  player_key: player_id
  team_key: team_id
  season_key: season
  season_as_int: true   # 2020 表示 2020-21

kg:
  use_season_nodes: true    # true: 季节建独立节点  false: season作为属性
  oncourt_source: data/processed/oncourt_core_for_kg.csv
  draft_source: data/processed/offcourt_draft.csv
  awards_source: data/processed/offcourt_awards.csv
  team_finance_source: data/processed/offcourt_team_finance.csv

modeling:
  feature_core_list: config/features_core.txt
  feature_full_json: reports/features/selected_features_full.json
  default_targets:
    - salary_cap_ratio
    - salary_cap_equiv
    - log_salary_cap_ratio
neo4j:
  uri: bolt://localhost:7687
  user: neo4j
  password_env: NEO4J_PASSWORD   # 从环境变量读取

